### ISSUE TITLE
captureDeepLinks crashes android app on resume

### ISSUE THREAD

**Issue by savv** [PostHog/posthog-react-native#1]
Calling `PostHog.setup` with the config below reliably crashes my android app with the config below, when I follow the following steps:
1. open app
2. wait for it to load
3. press the back button
4. open again

.. with the following stack trace on Android:
```
10-13 21:18:50.657 19522 19522 E AndroidRuntime: Process: com.greentriangle.greentriangle, PID: 19522
10-13 21:18:50.657 19522 19522 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.greentriangle.greentriangle/com.greentriangle.greentriangle.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.net.Uri.getQueryParameterNames()' on a null object reference
```

I'm on RN 0.63.3. Disabling captureDeepLinks makes the issue go away.

```
{
    host: 'https://app.posthog.com',
    captureApplicationLifecycleEvents: true,
    captureDeepLinks: true,
    recordScreenViews: true,
    flushInterval: 30,
    flushAt: 20,
    ios: {
      capturePushNotifications: false,
    },
  }
```

**Comment by benjackwhite** [comment]
Closing this with the release of v2.0.0 as we now have a completely refactored "pure" Javascript implementation which avoids native crossover issues like these
