### ISSUE TITLE
iOS build crashing (duplicate symbol)

### ISSUE THREAD

**Issue by serhey-dev** [PostHog/posthog-react-native#2]
Hi there,

We are using version 1.0.1 of this package together with https://github.com/segmentio/analytics-react-native (version 1.3.1).
We noticed, that when we are building our app for iOS (doesn't matter simulator or a real device), we are facing such issue.

Issue screenshot:
![1111](https://user-images.githubusercontent.com/37838803/100430641-bb957680-309f-11eb-9483-9d67a4cf4026.jpeg)

Environment:
`
React Native: 0.63.2;
XCode version: 12;
Simulator/device: iPhone Xr, iOS 14;
`

At the same time Android build works well.
Does anyone here know what might be wrong and how this issue can be fixed?

**Comment by timgl** [comment]
@lyshchenkosergiy Sorry for the late response. I think the reason for this is that our react-native library is based on Segment's one, so that's why there's a conflict. We have [a segment integration](https://posthog.com/docs/integrations/segment-integration) so you could just turn that on as an easy fix instead.

**Comment by serhey-dev** [comment]
@timgl I tried to contribute to the iOS repo with the fix for this issue - https://github.com/PostHog/posthog-ios. But unfortunately I'm not able to push feature branch (permission denied) in order to create pull request. Does PostHog accept contributions from community and is there any chance I can create a pull request?

**Comment by timgl** [comment]
@serhey-dev Hey, I think you'll need to "fork" the repository first, then you can create a pull request back into that repo. There's some instructions here: https://mattstauffer.com/blog/how-to-contribute-to-an-open-source-github-project-using-your-own-fork/

**Comment by serhey-dev** [comment]
@timgl https://github.com/PostHog/posthog-ios/pull/9 I just added a Pull Request to ios package repo. This should fix the issue with build on iOS.

**Comment by mariusandra** [comment]
Hey @serhey-dev I've finally released `1.1.1` that includes your iOS patch. Please let us know if it works fine or if there are any other issues we can help with.
