### ISSUE TITLE
Add support for feature flags

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog-react-native#25]
Part of a push to add feature flags to commonly used libraries.

**Comment by mariusandra** [comment]
@yakkomajuri This package is just a thin wrapper around the iOS and Android libraries, so if you want to add feature flags here, you need to add them to both mobile libraries first.

**Comment by yakkomajuri** [comment]
Hmm yeah hadn't looked into it when we did sprint planning today. I guess I could write a feature flags layer in JS though as long as I can get the user's distinct ID?

**Comment by mariusandra** [comment]
The main reason this library uses some native bindings is to get some basic screen name and whatnot autocapture working. Plus some native apis to get more context ($something in properties). 

I guess such a layer for feature flags could be possible. 

There is also the much requested feature of expo support https://github.com/PostHog/posthog/issues/1174 (aka pure js react native). This code could be shared between both when the expo plugin gets built.

**Comment by benjackwhite** [comment]
Done in v2.0.0
