### ISSUE TITLE
Automatic `recordScreenViews` not working in Android & iOS (simulator environment)

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog-react-native#29]
A user indicated that this feature was not working for them: 

>  I am trying to use automatic `recordScreenViews` in react-native. In the android simulator no `$screen` events are captured and on the iOS simulator the only screen names I get are `UI` and `RCTModalHost` . Am I missing something additional I have to do to make this work?

The user confirmed that manually sending a screen view works.

**Comment by benjackwhite** [comment]
This was a factor of our limited v1 implementation. v2 is fully built for React Native and hooks into the react-native-navigation stack.
