### ISSUE TITLE
Update PostHog pod version to 1.1.0

### ISSUE THREAD

**Issue by artshin** [PostHog/posthog-react-native#3]
Hey there!

Was wandering if this package could be updated with the latest `PostHog` `1.1.0` version? It has this functionality https://github.com/PostHog/posthog-ios/pull/5 which we direly need to avoid app rejections in AppStore.

Thanks in advance!

**Comment by mariusandra** [comment]
Hey! Version 1.1.0 of the react native library released! It includes posthog-ios 1.2.1, that removes ad capturing.
