### ISSUE TITLE
Cannot build for Android: forEach((Map.Entry<K, V>) -> Unit): Unit' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3

### ISSUE THREAD

**Issue by indapublic** [PostHog/posthog-react-native#42]
```"posthog-react-native": "^1.1.3"```

> Task :posthog-react-native:compileReleaseKotlin
e: .../node_modules/posthog-react-native/android/src/main/java/com/posthog/reactnative/core/RNPostHogModule.kt: (236, 27): 'forEach((Map.Entry<K, V>) -> Unit): Unit' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3

Tried add `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"` to `android/build.gradle` but no success

**Comment by timgl** [comment]
Hey @indapublic,  thanks for raising this. Is there any chance you could open a PR with a fix? Thanks so much in advance!

**Comment by ivari** [comment]
Also seeing this issue.

**Comment by yakkomajuri** [comment]
Fix merged in #46
