### ISSUE TITLE
Android, checkParameterIsNotNull, parameter distinctId

### ISSUE THREAD

**Issue by Cavallando** [PostHog/posthog-react-native#49]
Hi,

We added Potshot to our Android react-native app and as the docs specify we pass `null` to distinctId when calling `.identify` when we don't have the user ID. This is not an issue for us on iOS but on Android our app immediately crashes.

When using an empty string `''` we do not see the crash on android.

**Comment by Cavallando** [comment]
Looking at the source code for this im going to open up an issue with posthog sdk

**Comment by mariusandra** [comment]
Hey, thanks for the PR! I published version 1.1.4 of the library with it. It's been a while since I last release a new version of this library, so I hope it all works. 🤞
