### ISSUE TITLE
Remove jcenter

### ISSUE THREAD

**Issue by erksch** [PostHog/posthog-react-native#59]
Hey there!

Please remove `jcenter()` from your `buildscript` repositories, as it is deprecated and regularly causes problems.

Other RN libraries also disable the `buildscript` block when the project is not the root project (when it's included as a library): https://github.com/react-native-netinfo/react-native-netinfo/blob/master/android/build.gradle#L5

**Comment by erksch** [comment]
https://github.com/PostHog/posthog-react-native/pull/60

**Comment by benjackwhite** [comment]
Closing this with the release of v2.0.0 as we now have a completely refactored "pure" Javascript implementation which avoids native crossover issues like these. Closing
