### ISSUE TITLE
PostHog React Native Automatically capturing $screen event

### ISSUE THREAD

**Issue by m-usman-yousuf** [PostHog/posthog-react-native#65]
RecordScreenViews and Lifecycle event are false but still capturing $screen events
![Screen Shot 2022-07-21 at 12 53 56 PM](https://user-images.githubusercontent.com/52995752/180160740-21cdebdd-cb40-4368-b51c-cb17d2aeca1c.png)
![Screen Shot 2022-07-21 at 12 55 37 PM](https://user-images.githubusercontent.com/52995752/180160819-11f689c9-4603-4b95-b719-6c563fd0ce33.png)

**Comment by benjackwhite** [comment]
We've just released v2 which is completely rebuilt with those options removed (they were options passed to the underlying `posthog-ios/android` libs which are no longer used in V2) and are replaced with hooks / or autocapture PostHogProvider which are much more reliably tested.

[Check out the docs for v2.0.0](https://posthog.com/docs/integrate/client/react-native) and let me know if this would solve your issue
