### ISSUE TITLE
Post Hog Integration Issue

### ISSUE THREAD

**Issue by m-usman-yousuf** [PostHog/posthog-react-native#67]
We are working on React Native CLI and PostHog V2 is not configuring properly. Please look into it.
I followed the official [docs.](url)
![Screen Shot 2022-08-19 at 2 59 12 PM](https://user-images.githubusercontent.com/52995752/185595100-4f8d07fb-6d70-41da-94fc-e774496edee3.png)

**Comment by benjackwhite** [comment]
It looks like you haven't installed the required peer dependencies https://posthog.com/docs/integrate/client/react-native#installation
