### ISSUE TITLE
posthog.reset(true) is not available on posthog react native

### ISSUE THREAD

**Issue by gcho91** [PostHog/posthog-react-native#71]
> posthog.reset() results in the device ID being reused for the anonymous ID. By default the existing device ID is reused, but if you'd like a fresh device ID to be generated instead, you should call posthog.reset(true). 

reset(true) is not available for react native. Can we have the same feature to allow users with multiple accounts to not be merged in the events? This also prevents adequate testing to be done while developing locally since all previous events with even a different email or unique ID get merged with old data.

**Comment by benjackwhite** [comment]
Where did you read that? Feels like something that might be outdated.

[Current docs](https://posthog.com/docs/integrate/client/react-native) are here and indicate it is possible.

**Comment by gcho91** [comment]
> Where did you read that? Feels like something that might be outdated.
> 
> [Current docs](https://posthog.com/docs/integrate/client/react-native) are here and indicate it is possible.

passing true results in this error: `Argument of type 'boolean' is not assignable to parameter of type 'PostHogPersistedProperty[]'`

**Comment by benjackwhite** [comment]
For react-native the API is slightly different (as you just shared). `.reset()`will reset all properties but you can pass in a special object to keep _some_ properties if needs be. This is very specific though, so you don't need to worry about it.
